# Generated by Django 2.1 on 2019-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
    ]
