# Generated by Django 2.1 on 2019-06-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_app', '0002_complain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineddata',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='mined_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
